version: '3'

services:
  postgres:
    image: postgres:14.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace-platform
    volumes:
      - ./docker_volumes/postgres-data:/var/lib/postgresql/data